name: "InnoSetup Cross"
description: "Cross-compile InnoSetup installers using Wine on Ubuntu."
inputs:
  filename:
    description: The .iss setup file to be compiled
    required: true

runs:
  using: composite
  steps:
    - name: Add i386 packages
      shell: bash
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
    
    - name: Install and cache packages
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: wine32 x11vnc xserver-xorg-video-dummy
        execute_install_scripts: true
        version: 1.0

    - name: Install and cache wine
      shell: bash
      run: sudo apt-get install wine

    - name: Install InnoSetup
      env:
        DISPLAY: :0.0
        WINEDEBUG: -all,err+all
      shell: bash
      run: |
        curl -SL "https://files.jrsoftware.org/is/6/innosetup-6.4.0.exe" -o is.exe
        sudo Xdummy :0 > /dev/null 2>&1 &
        wine is.exe /SP- /VERYSILENT /ALLUSERS /SUPPRESSMSGBOXES /DOWNLOADISCRYPT=1
        rm is.exe

        cd "$HOME/.wine/drive_c/Program Files/Inno Setup 6/Languages"
        curl -L "https://api.github.com/repos/jrsoftware/issrc/tarball/is-6_4_0" | tar xz --strip-components=4 --wildcards "*/Files/Languages/Unofficial/*.isl"
      
    - name: Build Inno Setup installer
      shell: bash
      env:
        WINEDEBUG: -all,err+all
      run: ${GITHUB_ACTION_PATH}/iscc.sh

