name: "InnoSetup Cross"
description: "Cross-compile InnoSetup installers using Wine on Ubuntu."
inputs:
  filename:
    description: The .iss setup file to be compiled
    required: true

runs:
  using: composite
  steps:
    - name: Add i386 architecture
      shell: bash
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update

    
    - name: Install and cache packages
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: wine32 x11vnc xserver-xorg-video-dummy
        execute_install_scripts: true
        version: 1.0

    # If wine is reinstalled from a cache, it cannot be found on the PATH, so it gets installed separately
    - name: Install wine without caching
      shell: bash
      run: sudo apt-get install -y wine

    - name: Cache InnoSetup
      id: cache-innosetup
      uses: actions/cache@v4
      with:
        path: ~/.wine/drive_c/Program Files (x86)/Inno Setup 6
        key: ${{ runner.os }}-innosetup

    - name: Install InnoSetup
      if: steps.cache-innosetup.outputs.cache-hit != 'true'
      env:
        DISPLAY: :0.0
        WINEDEBUG: -all,err+all
      shell: bash
      run: ${GITHUB_ACTION_PATH}/install_iscc.sh
      
    - name: Build Inno Setup installer
      env:
        WINEDEBUG: -all,err+all
      shell: bash
      run: ${GITHUB_ACTION_PATH}/iscc.sh ${{ inputs.filename }}

