name: "InnoSetup Cross"
description: "Cross-compile InnoSetup installers using Wine on Ubuntu."
inputs:
  filename:
    description: The .iss setup file to be compiled
    required: true

runs:
  using: composite
  steps:
    - name: Install Wine
      shell: bash
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y wine wine32
        sudo apt-get install -y x11vnc xserver-xorg-video-dummy

    - name: Install InnoSetup
      env:
        DISPLAY: :0.0
        WINEDEBUG: -all,err+all
      shell: bash
      run: |
        curl -SL "https://files.jrsoftware.org/is/6/innosetup-6.4.0.exe" -o is.exe
        sudo Xdummy :0 > /dev/null 2>&1 &
        wine is.exe /SP- /VERYSILENT /ALLUSERS /SUPPRESSMSGBOXES /DOWNLOADISCRYPT=1
        rm is.exe
      
    - name: Build Inno Setup installer
      shell: bash
      env:
        WINEDEBUG: -all,err+all
      run: ${GITHUB_ACTION_PATH}/iscc.sh

