name: Tests
on:
  push

jobs:
  test-build-installer:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Installer
        uses: ./
        with:
          filename: Test.iss