name: Tests
on:
  push

jobs:
  test-build-installer:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build installer
        uses: ./
        with:
          filename: Test.iss

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ActionTestInstaller.exe
          path: Output/ActionTestInstaller.exe
          if-no-files-found: error
          